default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("DB_POOL", 25)%>
  timeout: 5000
  reaping_frequency: <%= Integer(ENV.fetch('DB_REAPING_FREQUENCY', 10)) %>
  min_messages: warning

# PRIMARY DATABASE
default_primary: &default_primary
  <<: *default
  host: <%= ENV.fetch("DB_HOST", 'db') %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  database: <%= ENV.fetch("DB_NAME", 'need-a-raise') %>
  username: <%= ENV.fetch("DB_USER", "postgres") %>
  password: <%= ENV.fetch("DB_PASS", "") %>
  prepared_statements: false # temporarily disable for pgbouncer testing

development:
  <<: *default_primary

production:
  <<: *default_primary

test:
  <<: *default_primary
  database: api_test
